### ISSUE TITLE
Crackling audio in dashboard

### ISSUE THREAD

**Issue by gfodor** [jellyfish-dev/jellyfish-dashboard#67]
Hello, I noticed that when running a local jellyfish instance with the dashboard, when connecting a peer from within the dashboard, the audio seems to stutter a bit, as though a buffer is being overrun. A test case with a local ogg file is now easy to set up (see https://github.com/jellyfish-dev/jellyfish-dashboard/pull/66)

The good news is that I don't hear this crackling when connecting a minimal react client, so it probably has something to do with the dashboard's implementation. I tried unplugging the fft analyzer from the media stream to no avail. I also noticed that if I pause the track via the speaker icon and unpause it seems to help, but you can still hear a slight stutter. Let me know if you have any trouble reproducing this and I can dig further. There were no errors in the log or anything that changed in the log when I resolved it with the mute/unmute trick. My guess is something is backing up in the Web Audio API.

**Comment by kamil-stasiak** [comment]
Hi, thanks for the report. We've fixed that issue in this (#68) pull request. It should be okay now
